name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build ./api/ -t abdelrhmanmasoud/qrcodebackend:latest
          docker build ./front-end-nextjs/ -t abdelrhmanmasoud/qrcodefrontend:latest

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_SECERET }}
          docker push abdelrhmanmasoud/qrcodebackend:latest
          docker push abdelrhmanmasoud/qrcodefrontend:latest
